Repository ttarlov/fit-lit-refactor-tractor, pull requests merged in 2020-04, with the labels that each got.

#13 Feature/jquery conversion
  package-lock.json
  package.json
  src/scripts.js
Labels: documentation

#18 Feature/fetch data
  src/api-controller.js
  src/scripts.js
Labels: enhancement

#30 Feature/sleep btn
  src/api-controller.js
  src/css/style.scss
  src/scripts.js
Labels: enhancement

#32 Feature/hydration post
  src/api-controller.js
  src/scripts.js
Labels: enhancement

#35 Feature/pop up card css
  src/css/style.scss
  src/index.html
  src/scripts.js
Labels: enhancement

#36 Chart.js
  package-lock.json
  package.json
  src/css/style.scss
  src/scripts.js
Labels: enhancement

#43 Inheritance
  src/Activity.js
  src/Calculator.js
  src/Hydration.js
  src/Sleep.js
  src/User-repo.js
  src/api-controller.js
  src/css/style.scss
  src/scripts.js
  test/hydration-test.js
  test/user-test.js
  test/userrepo-test.js
Labels: bug, dependencies, enhancement

#45 Bug fix/undefined winner
  src/Activity.js
  src/scripts.js
Labels: bug

#54 Feature/dom updates
  src/Activity.js
  src/Calculator.js
  src/Sleep.js
  src/User-repo.js
  src/User.js
  src/api-controller.js
  src/dom-updates.js
  src/index.html
  src/scripts.js
  test/activity-test.js
  test/userrepo-test.js
Labels: dependencies, enhancement

#56 Styling bug fix
  src/css/_main.scss
  src/css/_sidebar.scss
  test/sleep-test.js
Labels: bug, dependencies

#57 Bug/form values
  src/Calculator.js
  src/api-controller.js
  src/dom-updates.js
Labels: bug

#59 Feature/aria
  src/css/_nav.scss
  src/css/_sidebar.scss
  src/css/_variables.scss
  src/index.html
Labels: enhancement

#61 Test fixes
  src/Activity.js
  src/Calculator.js
  src/Sleep.js
  src/User-repo.js
  src/dom-updates.js
  src/scripts.js
  test/activity-test.js
  test/calculator-test.js
  test/hydration-test.js
  test/sleep-test.js
  test/userrepo-test.js
Labels: enhancement

#62 Feature/classes inherit
  src/Activity.js
  src/Calculator.js
  src/Hydration.js
  src/Sleep.js
  src/User-repo.js
  src/dom-updates.js
  src/scripts.js
  test/sleep-test.js
Labels: documentation

#64 Feature/lint
  src/Activity.js
  src/Calculator.js
  src/Hydration.js
  src/Sleep.js
  src/User-repo.js
  src/api-controller.js
  src/css/_sidebar.scss
  src/css/style.scss
  src/dom-updates.js
  src/index.js
  src/scripts.js
  test/activity-test.js
  test/calculator-test.js
  test/hydration-test.js
  test/sleep-test.js
  test/user-test.js
  test/userrepo-test.js
Labels: documentation
